#!/bin/bash

set -e

print_error() {
  >&2 echo -e "$@"
}

fail() {
  print_error "$@"
  exit 1
}

get_secret() {
  local name="$1"

  local sfile="/etc/secrets/${name}"
  [[ ! -r $sfile ]] && fail "can not read ${sfile}"

  # oh ya, bash 4.x baby!
  local var_name="${name^^}"
  local sdata
  sdata=$(<"$sfile")

  eval "export ${var_name}=${sdata}"
}

get_secret AWS_ACCESS_KEY_ID
get_secret AWS_SECRET_ACCESS_KEY
get_secret S3_BUCKET

WWW_ROOT='/var/www/html'

# compare both size and timestamp; this is needed to detect s3 objects which
# have been replaced with a new version that has the same size.
aws s3 sync --exact-timestamps --delete "s3://${S3_BUCKET}" "$WWW_ROOT"
find "$WWW_ROOT" -depth -type d -empty -delete
